# ============================
# Autopilot Governance (FULL)
# ============================

# متى نعتبر الإعداد ناجح ونعتمده للتداول / التشغيل؟
acceptance:
  # تأكيد كامل النافذة
  confirm_min_pf: 1.05         # لازم PF ≥ 1.05
  confirm_min_trades: 100      # أقل عدد صفقات للتأكيد
  confirm_max_dd_pct: 4.0      # أقصى سحب مسموح
  confirm_min_win_pct: 45.0    # توازن مقبول للـWin%

  # Walk-Forward (آخر 60 يوم)
  walk_min_pf: 0.95            # لازم ما ينهار
  walk_max_dd_pct: 5.0
  walk_min_trades: 40

  # سياسات الاستكشاف
  freeze_hours_after_promote: 24  # بعد اعتماد إعداد، لا تروّج واحد جديد قبل هذا الزمن
  max_retries_if_no_trades: 12    # كم مرة نرخي الشروط تلقائيًا إذا ما في صفقات قبل ما نترك الإعداد

# إعدادات البحث (Wide -> Narrow)
search:
  # مؤقتًا ركّز على M5 لتحقيق PF>1، بعد النجاح رجّع M15/H1
  tfs: ["M5"]

  # حجم البحث
  trials_wide: 120
  trials_narrow: 300

  # أهداف الجودة
  target_pf: 1.08              # شدّ الهدف شوي عشان ما نقبل الهش
  dd_cap: 20.0                 # سقف سحب أثناء التقييم
  min_trades: 90               # أقل صفقات نطلبها من أي تجربة

# حراس السوق/التكلفة أثناء الاستكشاف (يُسحب منها نطاقات للعينات)
guards:
  # لازم حركة دنيا (ATR% من السعر)
  min_atr_pct_wide:   [0.0009, 0.0013]
  min_atr_pct_narrow: [0.0010, 0.0013]

  # لا ندخل لو التكلفة (spread+slip) كبيرة نسبةً للـATR
  max_spread_vs_atr_wide:   [0.20, 0.24]
  max_spread_vs_atr_narrow: [0.20, 0.23]

  # سقف صفقات يومي لتجنب الإفراط
  max_trades_per_day: [70, 90]

# تشغيل دوري (لو بدك الأوتوبيلوت يلف لحاله)
loop:
  enabled: false
  hours: 6

# ————————————————————————————————
# ملاحظات تشغيلية:
# - لو بدك توسّع لاحقًا: غيّر search.tfs إلى ["M5","M15"] أو أضف "H1".
# - لو الاستكشاف صار بطيء: قلّل trials_narrow أو زوّد loop.hours.
# - الأوتوبايلوت يرخّي الشروط تلقائيًا عند "لا توجد صفقات" لحد max_retries_if_no_trades.
# - الهدف الآن رفع PF بثبات على M5؛ لما نتجاوز 1.05 مع WalkFwd ≥0.95، رجّع M15 للمقارنة.
# ————————————————————————————————
